version: "3.5"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
      - database.env
      # - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
      # - DB_UPSTREAM=http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:5432

    volumes:
      - postgres:${PGDATA}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    # networks:
    #   - gfnetwork
    networks:
      - postgres
    restart: unless-stopped
    # network_mode: host

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - database.env
      # - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - postgres
    restart: unless-stopped

  graphql-engine:
    image: fedormelexin/graphql-engine-arm64
    # image: hasura/graphql-engine:v2.0.1
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    env_file:
      - database.env
    environment:
      # For MacOS
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${MACOS_PORT}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
      ## For Linux Chads
      # HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      # HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:example@host.docker.internal:5432/recipes
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

networks:
  # For Global networking
  # gfnetwork:
  #   external: true
  postgres:
    # driver: bridge
    ## TODO: This is for Mac
    driver: host

volumes:
  postgres:
  pgadmin:
