version: "3.5"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
      - database.env
      # - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
      # - DB_UPSTREAM=http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:5432

    volumes:
      - postgres:${PGDATA}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    # networks:
    #   - gfnetwork
    networks:
      - postgres
    restart: unless-stopped
    # network_mode: host

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - database.env
      # - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - postgres
    restart: unless-stopped

networks:
  # For Global networking
  # gfnetwork:
  #   external: true
  postgres:
    driver: bridge
    ## TODO: This is for Mac
    # driver: host

volumes:
  postgres:
  pgadmin:
